// Code generated by Slice Machine. DO NOT EDIT.

import Links from './Links';
import TextRepeater from './TextRepeater';
import Titleseeeee from './Titleseeeee';

export {
	Links,
	TextRepeater,
	Titleseeeee,
};

export const components = {
	links: Links,
	text_repeater: TextRepeater,
	landing_page: Titleseeeee,
};
